def macarena 
  puts "Put your right arm out"
  puts "Put your left arm out"
  puts "Flip right palm"
  puts "Flip left palm"
  puts "Right arm, left shoulder"
  puts "Left arm, right shoulder"
  puts "Right arm to your head"
  puts "Left arm to your head"
  puts "Right arm, left hip"
  puts "Left arm, right hip"
  puts "Right arm, right hip"
  puts "Left arm, left hip"
  puts "ayyyyyyyyyy macarena(turn)"
